scraping:
  default_delay: 1.0
  max_requests_per_minute: 60
  user_agent: "Epoch AI Model Tracker 0.1.0"
  timeout: 30

sources:
  lmarena:
    enabled: true
    data_dir: "data/raw/lmarena/text"
  
  company_blogs:
    enabled: true
    delay: 2.0
    sources:
      - name: "anthropic"
        url: "https://www.anthropic.com/news"
      - name: "meta"
        url: "https://ai.meta.com/blog"
      - name: "openai"
        url: "https://openai.com/index"
      - name: "google_deepmind"
        url: "https://deepmind.google/research"

storage:
  data_dir: "./data"
  format: "json"
  backup: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/epoch_tracker.log"